version: "3.7"
services:
  
  app:
    build:
      context: .
    ports: 
      - "8080:8080"
    volumes:
      - ./app:/app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    env_file:
      - ./app.env
    depends_on: 
      - db
  
  db:
    image: postgres:latest
    env_file:
      - ./db.env
    ports:
      - "5432:5432"
    volumes: 
      - tutorial-volume:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./pgadmin.env
    ports: 
      - "4040:80"
    depends_on:
      - db

volumes: 
  tutorial-volume: